name: pretty_good_secure_folder

description: "A new Flutter project."

publish_to: 'none'

version: 1.2.0+4

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  # State management
  riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  hooks_riverpod: ^3.0.3
  flutter_hooks: ^0.21.3+1
  freezed_annotation: ^3.1.0

  # Routing
  go_router: ^14.6.2

  # isar(NoSQL)
  isar_community: ^3.3.0
  isar_community_flutter_libs: ^3.3.0

  # Slider item
  flutter_slidable: ^4.0.3

  # Toast
  toastification: ^3.0.3

  path_provider: ^2.1.5

  intl: ^0.20.2

  # shared_preferences
  shared_preferences: ^2.5.3

  # pgp
  openpgp: ^3.10.7

  # logger
  logger: ^2.6.2

  # searchbar
  animated_search_bar: ^2.8.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Code generation
  build_runner: ^2.4.13
  riverpod_generator: ^3.0.3
  custom_lint: ^0.8.0
  riverpod_lint: ^3.0.3
  freezed: ^3.2.3
  uuid: ^4.5.2

  isar_community_generator: ^3.3.0
  flutter_gen_runner: ^5.12.0

  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon/icon.png"

flutter_gen:
  assets:
    outputs:
      package_parameter_enabled: true
    enabled: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package